// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package association

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AlarmConfiguration, b.ko.Spec.AlarmConfiguration) {
		delta.Add("Spec.AlarmConfiguration", a.ko.Spec.AlarmConfiguration, b.ko.Spec.AlarmConfiguration)
	} else if a.ko.Spec.AlarmConfiguration != nil && b.ko.Spec.AlarmConfiguration != nil {
		if len(a.ko.Spec.AlarmConfiguration.Alarms) != len(b.ko.Spec.AlarmConfiguration.Alarms) {
			delta.Add("Spec.AlarmConfiguration.Alarms", a.ko.Spec.AlarmConfiguration.Alarms, b.ko.Spec.AlarmConfiguration.Alarms)
		} else if len(a.ko.Spec.AlarmConfiguration.Alarms) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.AlarmConfiguration.Alarms, b.ko.Spec.AlarmConfiguration.Alarms) {
				delta.Add("Spec.AlarmConfiguration.Alarms", a.ko.Spec.AlarmConfiguration.Alarms, b.ko.Spec.AlarmConfiguration.Alarms)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure, b.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure) {
			delta.Add("Spec.AlarmConfiguration.IgnorePollAlarmFailure", a.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure, b.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure)
		} else if a.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure != nil && b.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure != nil {
			if *a.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure != *b.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure {
				delta.Add("Spec.AlarmConfiguration.IgnorePollAlarmFailure", a.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure, b.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ApplyOnlyAtCronInterval, b.ko.Spec.ApplyOnlyAtCronInterval) {
		delta.Add("Spec.ApplyOnlyAtCronInterval", a.ko.Spec.ApplyOnlyAtCronInterval, b.ko.Spec.ApplyOnlyAtCronInterval)
	} else if a.ko.Spec.ApplyOnlyAtCronInterval != nil && b.ko.Spec.ApplyOnlyAtCronInterval != nil {
		if *a.ko.Spec.ApplyOnlyAtCronInterval != *b.ko.Spec.ApplyOnlyAtCronInterval {
			delta.Add("Spec.ApplyOnlyAtCronInterval", a.ko.Spec.ApplyOnlyAtCronInterval, b.ko.Spec.ApplyOnlyAtCronInterval)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AssociationName, b.ko.Spec.AssociationName) {
		delta.Add("Spec.AssociationName", a.ko.Spec.AssociationName, b.ko.Spec.AssociationName)
	} else if a.ko.Spec.AssociationName != nil && b.ko.Spec.AssociationName != nil {
		if *a.ko.Spec.AssociationName != *b.ko.Spec.AssociationName {
			delta.Add("Spec.AssociationName", a.ko.Spec.AssociationName, b.ko.Spec.AssociationName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AutomationTargetParameterName, b.ko.Spec.AutomationTargetParameterName) {
		delta.Add("Spec.AutomationTargetParameterName", a.ko.Spec.AutomationTargetParameterName, b.ko.Spec.AutomationTargetParameterName)
	} else if a.ko.Spec.AutomationTargetParameterName != nil && b.ko.Spec.AutomationTargetParameterName != nil {
		if *a.ko.Spec.AutomationTargetParameterName != *b.ko.Spec.AutomationTargetParameterName {
			delta.Add("Spec.AutomationTargetParameterName", a.ko.Spec.AutomationTargetParameterName, b.ko.Spec.AutomationTargetParameterName)
		}
	}
	if len(a.ko.Spec.CalendarNames) != len(b.ko.Spec.CalendarNames) {
		delta.Add("Spec.CalendarNames", a.ko.Spec.CalendarNames, b.ko.Spec.CalendarNames)
	} else if len(a.ko.Spec.CalendarNames) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.CalendarNames, b.ko.Spec.CalendarNames) {
			delta.Add("Spec.CalendarNames", a.ko.Spec.CalendarNames, b.ko.Spec.CalendarNames)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ComplianceSeverity, b.ko.Spec.ComplianceSeverity) {
		delta.Add("Spec.ComplianceSeverity", a.ko.Spec.ComplianceSeverity, b.ko.Spec.ComplianceSeverity)
	} else if a.ko.Spec.ComplianceSeverity != nil && b.ko.Spec.ComplianceSeverity != nil {
		if *a.ko.Spec.ComplianceSeverity != *b.ko.Spec.ComplianceSeverity {
			delta.Add("Spec.ComplianceSeverity", a.ko.Spec.ComplianceSeverity, b.ko.Spec.ComplianceSeverity)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DocumentVersion, b.ko.Spec.DocumentVersion) {
		delta.Add("Spec.DocumentVersion", a.ko.Spec.DocumentVersion, b.ko.Spec.DocumentVersion)
	} else if a.ko.Spec.DocumentVersion != nil && b.ko.Spec.DocumentVersion != nil {
		if *a.ko.Spec.DocumentVersion != *b.ko.Spec.DocumentVersion {
			delta.Add("Spec.DocumentVersion", a.ko.Spec.DocumentVersion, b.ko.Spec.DocumentVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Duration, b.ko.Spec.Duration) {
		delta.Add("Spec.Duration", a.ko.Spec.Duration, b.ko.Spec.Duration)
	} else if a.ko.Spec.Duration != nil && b.ko.Spec.Duration != nil {
		if *a.ko.Spec.Duration != *b.ko.Spec.Duration {
			delta.Add("Spec.Duration", a.ko.Spec.Duration, b.ko.Spec.Duration)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InstanceID, b.ko.Spec.InstanceID) {
		delta.Add("Spec.InstanceID", a.ko.Spec.InstanceID, b.ko.Spec.InstanceID)
	} else if a.ko.Spec.InstanceID != nil && b.ko.Spec.InstanceID != nil {
		if *a.ko.Spec.InstanceID != *b.ko.Spec.InstanceID {
			delta.Add("Spec.InstanceID", a.ko.Spec.InstanceID, b.ko.Spec.InstanceID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxConcurrency, b.ko.Spec.MaxConcurrency) {
		delta.Add("Spec.MaxConcurrency", a.ko.Spec.MaxConcurrency, b.ko.Spec.MaxConcurrency)
	} else if a.ko.Spec.MaxConcurrency != nil && b.ko.Spec.MaxConcurrency != nil {
		if *a.ko.Spec.MaxConcurrency != *b.ko.Spec.MaxConcurrency {
			delta.Add("Spec.MaxConcurrency", a.ko.Spec.MaxConcurrency, b.ko.Spec.MaxConcurrency)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaxErrors, b.ko.Spec.MaxErrors) {
		delta.Add("Spec.MaxErrors", a.ko.Spec.MaxErrors, b.ko.Spec.MaxErrors)
	} else if a.ko.Spec.MaxErrors != nil && b.ko.Spec.MaxErrors != nil {
		if *a.ko.Spec.MaxErrors != *b.ko.Spec.MaxErrors {
			delta.Add("Spec.MaxErrors", a.ko.Spec.MaxErrors, b.ko.Spec.MaxErrors)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OutputLocation, b.ko.Spec.OutputLocation) {
		delta.Add("Spec.OutputLocation", a.ko.Spec.OutputLocation, b.ko.Spec.OutputLocation)
	} else if a.ko.Spec.OutputLocation != nil && b.ko.Spec.OutputLocation != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.OutputLocation.S3Location, b.ko.Spec.OutputLocation.S3Location) {
			delta.Add("Spec.OutputLocation.S3Location", a.ko.Spec.OutputLocation.S3Location, b.ko.Spec.OutputLocation.S3Location)
		} else if a.ko.Spec.OutputLocation.S3Location != nil && b.ko.Spec.OutputLocation.S3Location != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.OutputLocation.S3Location.OutputS3BucketName, b.ko.Spec.OutputLocation.S3Location.OutputS3BucketName) {
				delta.Add("Spec.OutputLocation.S3Location.OutputS3BucketName", a.ko.Spec.OutputLocation.S3Location.OutputS3BucketName, b.ko.Spec.OutputLocation.S3Location.OutputS3BucketName)
			} else if a.ko.Spec.OutputLocation.S3Location.OutputS3BucketName != nil && b.ko.Spec.OutputLocation.S3Location.OutputS3BucketName != nil {
				if *a.ko.Spec.OutputLocation.S3Location.OutputS3BucketName != *b.ko.Spec.OutputLocation.S3Location.OutputS3BucketName {
					delta.Add("Spec.OutputLocation.S3Location.OutputS3BucketName", a.ko.Spec.OutputLocation.S3Location.OutputS3BucketName, b.ko.Spec.OutputLocation.S3Location.OutputS3BucketName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix, b.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix) {
				delta.Add("Spec.OutputLocation.S3Location.OutputS3KeyPrefix", a.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix, b.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix)
			} else if a.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix != nil && b.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				if *a.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix != *b.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix {
					delta.Add("Spec.OutputLocation.S3Location.OutputS3KeyPrefix", a.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix, b.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.OutputLocation.S3Location.OutputS3Region, b.ko.Spec.OutputLocation.S3Location.OutputS3Region) {
				delta.Add("Spec.OutputLocation.S3Location.OutputS3Region", a.ko.Spec.OutputLocation.S3Location.OutputS3Region, b.ko.Spec.OutputLocation.S3Location.OutputS3Region)
			} else if a.ko.Spec.OutputLocation.S3Location.OutputS3Region != nil && b.ko.Spec.OutputLocation.S3Location.OutputS3Region != nil {
				if *a.ko.Spec.OutputLocation.S3Location.OutputS3Region != *b.ko.Spec.OutputLocation.S3Location.OutputS3Region {
					delta.Add("Spec.OutputLocation.S3Location.OutputS3Region", a.ko.Spec.OutputLocation.S3Location.OutputS3Region, b.ko.Spec.OutputLocation.S3Location.OutputS3Region)
				}
			}
		}
	}
	if len(a.ko.Spec.Parameters) != len(b.ko.Spec.Parameters) {
		delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
	} else if len(a.ko.Spec.Parameters) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Parameters, b.ko.Spec.Parameters) {
			delta.Add("Spec.Parameters", a.ko.Spec.Parameters, b.ko.Spec.Parameters)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression) {
		delta.Add("Spec.ScheduleExpression", a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression)
	} else if a.ko.Spec.ScheduleExpression != nil && b.ko.Spec.ScheduleExpression != nil {
		if *a.ko.Spec.ScheduleExpression != *b.ko.Spec.ScheduleExpression {
			delta.Add("Spec.ScheduleExpression", a.ko.Spec.ScheduleExpression, b.ko.Spec.ScheduleExpression)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ScheduleOffset, b.ko.Spec.ScheduleOffset) {
		delta.Add("Spec.ScheduleOffset", a.ko.Spec.ScheduleOffset, b.ko.Spec.ScheduleOffset)
	} else if a.ko.Spec.ScheduleOffset != nil && b.ko.Spec.ScheduleOffset != nil {
		if *a.ko.Spec.ScheduleOffset != *b.ko.Spec.ScheduleOffset {
			delta.Add("Spec.ScheduleOffset", a.ko.Spec.ScheduleOffset, b.ko.Spec.ScheduleOffset)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SyncCompliance, b.ko.Spec.SyncCompliance) {
		delta.Add("Spec.SyncCompliance", a.ko.Spec.SyncCompliance, b.ko.Spec.SyncCompliance)
	} else if a.ko.Spec.SyncCompliance != nil && b.ko.Spec.SyncCompliance != nil {
		if *a.ko.Spec.SyncCompliance != *b.ko.Spec.SyncCompliance {
			delta.Add("Spec.SyncCompliance", a.ko.Spec.SyncCompliance, b.ko.Spec.SyncCompliance)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if len(a.ko.Spec.TargetLocations) != len(b.ko.Spec.TargetLocations) {
		delta.Add("Spec.TargetLocations", a.ko.Spec.TargetLocations, b.ko.Spec.TargetLocations)
	} else if len(a.ko.Spec.TargetLocations) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetLocations, b.ko.Spec.TargetLocations) {
			delta.Add("Spec.TargetLocations", a.ko.Spec.TargetLocations, b.ko.Spec.TargetLocations)
		}
	}
	if len(a.ko.Spec.Targets) != len(b.ko.Spec.Targets) {
		delta.Add("Spec.Targets", a.ko.Spec.Targets, b.ko.Spec.Targets)
	} else if len(a.ko.Spec.Targets) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Targets, b.ko.Spec.Targets) {
			delta.Add("Spec.Targets", a.ko.Spec.Targets, b.ko.Spec.Targets)
		}
	}

	return delta
}
