// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package association

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/ssm"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/ssm/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ssm-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Association{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeAssociationOutput
	resp, err = rm.sdkapi.DescribeAssociation(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeAssociation", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "AssociationDoesNotExist" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.AssociationDescription.AlarmConfiguration != nil {
		f0 := &svcapitypes.AlarmConfiguration{}
		if resp.AssociationDescription.AlarmConfiguration.Alarms != nil {
			f0f0 := []*svcapitypes.Alarm{}
			for _, f0f0iter := range resp.AssociationDescription.AlarmConfiguration.Alarms {
				f0f0elem := &svcapitypes.Alarm{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = f0f0iter.Name
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.Alarms = f0f0
		}
		f0.IgnorePollAlarmFailure = &resp.AssociationDescription.AlarmConfiguration.IgnorePollAlarmFailure
		ko.Spec.AlarmConfiguration = f0
	} else {
		ko.Spec.AlarmConfiguration = nil
	}
	ko.Spec.ApplyOnlyAtCronInterval = &resp.AssociationDescription.ApplyOnlyAtCronInterval
	if resp.AssociationDescription.AssociationId != nil {
		ko.Status.AssociationID = resp.AssociationDescription.AssociationId
	} else {
		ko.Status.AssociationID = nil
	}
	if resp.AssociationDescription.AssociationName != nil {
		ko.Spec.AssociationName = resp.AssociationDescription.AssociationName
	} else {
		ko.Spec.AssociationName = nil
	}
	if resp.AssociationDescription.AssociationVersion != nil {
		ko.Status.AssociationVersion = resp.AssociationDescription.AssociationVersion
	} else {
		ko.Status.AssociationVersion = nil
	}
	if resp.AssociationDescription.AutomationTargetParameterName != nil {
		ko.Spec.AutomationTargetParameterName = resp.AssociationDescription.AutomationTargetParameterName
	} else {
		ko.Spec.AutomationTargetParameterName = nil
	}
	if resp.AssociationDescription.CalendarNames != nil {
		ko.Spec.CalendarNames = aws.StringSlice(resp.AssociationDescription.CalendarNames)
	} else {
		ko.Spec.CalendarNames = nil
	}
	if resp.AssociationDescription.ComplianceSeverity != "" {
		ko.Spec.ComplianceSeverity = aws.String(string(resp.AssociationDescription.ComplianceSeverity))
	} else {
		ko.Spec.ComplianceSeverity = nil
	}
	if resp.AssociationDescription.Date != nil {
		ko.Status.Date = &metav1.Time{*resp.AssociationDescription.Date}
	} else {
		ko.Status.Date = nil
	}
	if resp.AssociationDescription.DocumentVersion != nil {
		ko.Spec.DocumentVersion = resp.AssociationDescription.DocumentVersion
	} else {
		ko.Spec.DocumentVersion = nil
	}
	if resp.AssociationDescription.Duration != nil {
		durationCopy := int64(*resp.AssociationDescription.Duration)
		ko.Spec.Duration = &durationCopy
	} else {
		ko.Spec.Duration = nil
	}
	if resp.AssociationDescription.InstanceId != nil {
		ko.Spec.InstanceID = resp.AssociationDescription.InstanceId
	} else {
		ko.Spec.InstanceID = nil
	}
	if resp.AssociationDescription.LastExecutionDate != nil {
		ko.Status.LastExecutionDate = &metav1.Time{*resp.AssociationDescription.LastExecutionDate}
	} else {
		ko.Status.LastExecutionDate = nil
	}
	if resp.AssociationDescription.LastSuccessfulExecutionDate != nil {
		ko.Status.LastSuccessfulExecutionDate = &metav1.Time{*resp.AssociationDescription.LastSuccessfulExecutionDate}
	} else {
		ko.Status.LastSuccessfulExecutionDate = nil
	}
	if resp.AssociationDescription.LastUpdateAssociationDate != nil {
		ko.Status.LastUpdateAssociationDate = &metav1.Time{*resp.AssociationDescription.LastUpdateAssociationDate}
	} else {
		ko.Status.LastUpdateAssociationDate = nil
	}
	if resp.AssociationDescription.MaxConcurrency != nil {
		ko.Spec.MaxConcurrency = resp.AssociationDescription.MaxConcurrency
	} else {
		ko.Spec.MaxConcurrency = nil
	}
	if resp.AssociationDescription.MaxErrors != nil {
		ko.Spec.MaxErrors = resp.AssociationDescription.MaxErrors
	} else {
		ko.Spec.MaxErrors = nil
	}
	if resp.AssociationDescription.Name != nil {
		ko.Spec.Name = resp.AssociationDescription.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.AssociationDescription.OutputLocation != nil {
		f18 := &svcapitypes.InstanceAssociationOutputLocation{}
		if resp.AssociationDescription.OutputLocation.S3Location != nil {
			f18f0 := &svcapitypes.S3OutputLocation{}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName != nil {
				f18f0.OutputS3BucketName = resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				f18f0.OutputS3KeyPrefix = resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region != nil {
				f18f0.OutputS3Region = resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region
			}
			f18.S3Location = f18f0
		}
		ko.Spec.OutputLocation = f18
	} else {
		ko.Spec.OutputLocation = nil
	}
	if resp.AssociationDescription.Overview != nil {
		f19 := &svcapitypes.AssociationOverview{}
		if resp.AssociationDescription.Overview.DetailedStatus != nil {
			f19.DetailedStatus = resp.AssociationDescription.Overview.DetailedStatus
		}
		if resp.AssociationDescription.Overview.Status != nil {
			f19.Status = resp.AssociationDescription.Overview.Status
		}
		ko.Status.Overview = f19
	} else {
		ko.Status.Overview = nil
	}
	if resp.AssociationDescription.Parameters != nil {
		f20 := map[string][]*string{}
		for f20key, f20valiter := range resp.AssociationDescription.Parameters {
			f20[f20key] = aws.StringSlice(f20valiter)
		}
		ko.Spec.Parameters = f20
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.AssociationDescription.ScheduleExpression != nil {
		ko.Spec.ScheduleExpression = resp.AssociationDescription.ScheduleExpression
	} else {
		ko.Spec.ScheduleExpression = nil
	}
	if resp.AssociationDescription.ScheduleOffset != nil {
		scheduleOffsetCopy := int64(*resp.AssociationDescription.ScheduleOffset)
		ko.Spec.ScheduleOffset = &scheduleOffsetCopy
	} else {
		ko.Spec.ScheduleOffset = nil
	}
	if resp.AssociationDescription.Status != nil {
		f23 := &svcapitypes.AssociationStatus_SDK{}
		if resp.AssociationDescription.Status.AdditionalInfo != nil {
			f23.AdditionalInfo = resp.AssociationDescription.Status.AdditionalInfo
		}
		if resp.AssociationDescription.Status.Date != nil {
			f23.Date = &metav1.Time{*resp.AssociationDescription.Status.Date}
		}
		if resp.AssociationDescription.Status.Message != nil {
			f23.Message = resp.AssociationDescription.Status.Message
		}
		if resp.AssociationDescription.Status.Name != "" {
			f23.Name = aws.String(string(resp.AssociationDescription.Status.Name))
		}
		ko.Status.Status = f23
	} else {
		ko.Status.Status = nil
	}
	if resp.AssociationDescription.SyncCompliance != "" {
		ko.Spec.SyncCompliance = aws.String(string(resp.AssociationDescription.SyncCompliance))
	} else {
		ko.Spec.SyncCompliance = nil
	}
	if resp.AssociationDescription.TargetLocations != nil {
		f25 := []*svcapitypes.TargetLocation{}
		for _, f25iter := range resp.AssociationDescription.TargetLocations {
			f25elem := &svcapitypes.TargetLocation{}
			if f25iter.Accounts != nil {
				f25elem.Accounts = aws.StringSlice(f25iter.Accounts)
			}
			if f25iter.ExcludeAccounts != nil {
				f25elem.ExcludeAccounts = aws.StringSlice(f25iter.ExcludeAccounts)
			}
			if f25iter.ExecutionRoleName != nil {
				f25elem.ExecutionRoleName = f25iter.ExecutionRoleName
			}
			f25elem.IncludeChildOrganizationUnits = &f25iter.IncludeChildOrganizationUnits
			if f25iter.Regions != nil {
				f25elem.Regions = aws.StringSlice(f25iter.Regions)
			}
			if f25iter.TargetLocationAlarmConfiguration != nil {
				f25elemf5 := &svcapitypes.AlarmConfiguration{}
				if f25iter.TargetLocationAlarmConfiguration.Alarms != nil {
					f25elemf5f0 := []*svcapitypes.Alarm{}
					for _, f25elemf5f0iter := range f25iter.TargetLocationAlarmConfiguration.Alarms {
						f25elemf5f0elem := &svcapitypes.Alarm{}
						if f25elemf5f0iter.Name != nil {
							f25elemf5f0elem.Name = f25elemf5f0iter.Name
						}
						f25elemf5f0 = append(f25elemf5f0, f25elemf5f0elem)
					}
					f25elemf5.Alarms = f25elemf5f0
				}
				f25elemf5.IgnorePollAlarmFailure = &f25iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure
				f25elem.TargetLocationAlarmConfiguration = f25elemf5
			}
			if f25iter.TargetLocationMaxConcurrency != nil {
				f25elem.TargetLocationMaxConcurrency = f25iter.TargetLocationMaxConcurrency
			}
			if f25iter.TargetLocationMaxErrors != nil {
				f25elem.TargetLocationMaxErrors = f25iter.TargetLocationMaxErrors
			}
			if f25iter.Targets != nil {
				f25elemf8 := []*svcapitypes.Target{}
				for _, f25elemf8iter := range f25iter.Targets {
					f25elemf8elem := &svcapitypes.Target{}
					if f25elemf8iter.Key != nil {
						f25elemf8elem.Key = f25elemf8iter.Key
					}
					if f25elemf8iter.Values != nil {
						f25elemf8elem.Values = aws.StringSlice(f25elemf8iter.Values)
					}
					f25elemf8 = append(f25elemf8, f25elemf8elem)
				}
				f25elem.Targets = f25elemf8
			}
			if f25iter.TargetsMaxConcurrency != nil {
				f25elem.TargetsMaxConcurrency = f25iter.TargetsMaxConcurrency
			}
			if f25iter.TargetsMaxErrors != nil {
				f25elem.TargetsMaxErrors = f25iter.TargetsMaxErrors
			}
			f25 = append(f25, f25elem)
		}
		ko.Spec.TargetLocations = f25
	} else {
		ko.Spec.TargetLocations = nil
	}
	if resp.AssociationDescription.Targets != nil {
		f26 := []*svcapitypes.Target{}
		for _, f26iter := range resp.AssociationDescription.Targets {
			f26elem := &svcapitypes.Target{}
			if f26iter.Key != nil {
				f26elem.Key = f26iter.Key
			}
			if f26iter.Values != nil {
				f26elem.Values = aws.StringSlice(f26iter.Values)
			}
			f26 = append(f26, f26elem)
		}
		ko.Spec.Targets = f26
	} else {
		ko.Spec.Targets = nil
	}
	if resp.AssociationDescription.TriggeredAlarms != nil {
		f27 := []*svcapitypes.AlarmStateInformation{}
		for _, f27iter := range resp.AssociationDescription.TriggeredAlarms {
			f27elem := &svcapitypes.AlarmStateInformation{}
			if f27iter.Name != nil {
				f27elem.Name = f27iter.Name
			}
			if f27iter.State != "" {
				f27elem.State = aws.String(string(f27iter.State))
			}
			f27 = append(f27, f27elem)
		}
		ko.Status.TriggeredAlarms = f27
	} else {
		ko.Status.TriggeredAlarms = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return false
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeAssociationInput, error) {
	res := &svcsdk.DescribeAssociationInput{}

	if r.ko.Status.AssociationID != nil {
		res.AssociationId = r.ko.Status.AssociationID
	}
	if r.ko.Status.AssociationVersion != nil {
		res.AssociationVersion = r.ko.Status.AssociationVersion
	}
	if r.ko.Spec.InstanceID != nil {
		res.InstanceId = r.ko.Spec.InstanceID
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateAssociationOutput
	_ = resp
	resp, err = rm.sdkapi.CreateAssociation(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateAssociation", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AssociationDescription.AlarmConfiguration != nil {
		f0 := &svcapitypes.AlarmConfiguration{}
		if resp.AssociationDescription.AlarmConfiguration.Alarms != nil {
			f0f0 := []*svcapitypes.Alarm{}
			for _, f0f0iter := range resp.AssociationDescription.AlarmConfiguration.Alarms {
				f0f0elem := &svcapitypes.Alarm{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = f0f0iter.Name
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.Alarms = f0f0
		}
		f0.IgnorePollAlarmFailure = &resp.AssociationDescription.AlarmConfiguration.IgnorePollAlarmFailure
		ko.Spec.AlarmConfiguration = f0
	} else {
		ko.Spec.AlarmConfiguration = nil
	}
	ko.Spec.ApplyOnlyAtCronInterval = &resp.AssociationDescription.ApplyOnlyAtCronInterval
	if resp.AssociationDescription.AssociationId != nil {
		ko.Status.AssociationID = resp.AssociationDescription.AssociationId
	} else {
		ko.Status.AssociationID = nil
	}
	if resp.AssociationDescription.AssociationName != nil {
		ko.Spec.AssociationName = resp.AssociationDescription.AssociationName
	} else {
		ko.Spec.AssociationName = nil
	}
	if resp.AssociationDescription.AssociationVersion != nil {
		ko.Status.AssociationVersion = resp.AssociationDescription.AssociationVersion
	} else {
		ko.Status.AssociationVersion = nil
	}
	if resp.AssociationDescription.AutomationTargetParameterName != nil {
		ko.Spec.AutomationTargetParameterName = resp.AssociationDescription.AutomationTargetParameterName
	} else {
		ko.Spec.AutomationTargetParameterName = nil
	}
	if resp.AssociationDescription.CalendarNames != nil {
		ko.Spec.CalendarNames = aws.StringSlice(resp.AssociationDescription.CalendarNames)
	} else {
		ko.Spec.CalendarNames = nil
	}
	if resp.AssociationDescription.ComplianceSeverity != "" {
		ko.Spec.ComplianceSeverity = aws.String(string(resp.AssociationDescription.ComplianceSeverity))
	} else {
		ko.Spec.ComplianceSeverity = nil
	}
	if resp.AssociationDescription.Date != nil {
		ko.Status.Date = &metav1.Time{*resp.AssociationDescription.Date}
	} else {
		ko.Status.Date = nil
	}
	if resp.AssociationDescription.DocumentVersion != nil {
		ko.Spec.DocumentVersion = resp.AssociationDescription.DocumentVersion
	} else {
		ko.Spec.DocumentVersion = nil
	}
	if resp.AssociationDescription.Duration != nil {
		durationCopy := int64(*resp.AssociationDescription.Duration)
		ko.Spec.Duration = &durationCopy
	} else {
		ko.Spec.Duration = nil
	}
	if resp.AssociationDescription.InstanceId != nil {
		ko.Spec.InstanceID = resp.AssociationDescription.InstanceId
	} else {
		ko.Spec.InstanceID = nil
	}
	if resp.AssociationDescription.LastExecutionDate != nil {
		ko.Status.LastExecutionDate = &metav1.Time{*resp.AssociationDescription.LastExecutionDate}
	} else {
		ko.Status.LastExecutionDate = nil
	}
	if resp.AssociationDescription.LastSuccessfulExecutionDate != nil {
		ko.Status.LastSuccessfulExecutionDate = &metav1.Time{*resp.AssociationDescription.LastSuccessfulExecutionDate}
	} else {
		ko.Status.LastSuccessfulExecutionDate = nil
	}
	if resp.AssociationDescription.LastUpdateAssociationDate != nil {
		ko.Status.LastUpdateAssociationDate = &metav1.Time{*resp.AssociationDescription.LastUpdateAssociationDate}
	} else {
		ko.Status.LastUpdateAssociationDate = nil
	}
	if resp.AssociationDescription.MaxConcurrency != nil {
		ko.Spec.MaxConcurrency = resp.AssociationDescription.MaxConcurrency
	} else {
		ko.Spec.MaxConcurrency = nil
	}
	if resp.AssociationDescription.MaxErrors != nil {
		ko.Spec.MaxErrors = resp.AssociationDescription.MaxErrors
	} else {
		ko.Spec.MaxErrors = nil
	}
	if resp.AssociationDescription.Name != nil {
		ko.Spec.Name = resp.AssociationDescription.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.AssociationDescription.OutputLocation != nil {
		f18 := &svcapitypes.InstanceAssociationOutputLocation{}
		if resp.AssociationDescription.OutputLocation.S3Location != nil {
			f18f0 := &svcapitypes.S3OutputLocation{}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName != nil {
				f18f0.OutputS3BucketName = resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				f18f0.OutputS3KeyPrefix = resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region != nil {
				f18f0.OutputS3Region = resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region
			}
			f18.S3Location = f18f0
		}
		ko.Spec.OutputLocation = f18
	} else {
		ko.Spec.OutputLocation = nil
	}
	if resp.AssociationDescription.Overview != nil {
		f19 := &svcapitypes.AssociationOverview{}
		if resp.AssociationDescription.Overview.DetailedStatus != nil {
			f19.DetailedStatus = resp.AssociationDescription.Overview.DetailedStatus
		}
		if resp.AssociationDescription.Overview.Status != nil {
			f19.Status = resp.AssociationDescription.Overview.Status
		}
		ko.Status.Overview = f19
	} else {
		ko.Status.Overview = nil
	}
	if resp.AssociationDescription.Parameters != nil {
		f20 := map[string][]*string{}
		for f20key, f20valiter := range resp.AssociationDescription.Parameters {
			f20[f20key] = aws.StringSlice(f20valiter)
		}
		ko.Spec.Parameters = f20
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.AssociationDescription.ScheduleExpression != nil {
		ko.Spec.ScheduleExpression = resp.AssociationDescription.ScheduleExpression
	} else {
		ko.Spec.ScheduleExpression = nil
	}
	if resp.AssociationDescription.ScheduleOffset != nil {
		scheduleOffsetCopy := int64(*resp.AssociationDescription.ScheduleOffset)
		ko.Spec.ScheduleOffset = &scheduleOffsetCopy
	} else {
		ko.Spec.ScheduleOffset = nil
	}
	if resp.AssociationDescription.Status != nil {
		f23 := &svcapitypes.AssociationStatus_SDK{}
		if resp.AssociationDescription.Status.AdditionalInfo != nil {
			f23.AdditionalInfo = resp.AssociationDescription.Status.AdditionalInfo
		}
		if resp.AssociationDescription.Status.Date != nil {
			f23.Date = &metav1.Time{*resp.AssociationDescription.Status.Date}
		}
		if resp.AssociationDescription.Status.Message != nil {
			f23.Message = resp.AssociationDescription.Status.Message
		}
		if resp.AssociationDescription.Status.Name != "" {
			f23.Name = aws.String(string(resp.AssociationDescription.Status.Name))
		}
		ko.Status.Status = f23
	} else {
		ko.Status.Status = nil
	}
	if resp.AssociationDescription.SyncCompliance != "" {
		ko.Spec.SyncCompliance = aws.String(string(resp.AssociationDescription.SyncCompliance))
	} else {
		ko.Spec.SyncCompliance = nil
	}
	if resp.AssociationDescription.TargetLocations != nil {
		f25 := []*svcapitypes.TargetLocation{}
		for _, f25iter := range resp.AssociationDescription.TargetLocations {
			f25elem := &svcapitypes.TargetLocation{}
			if f25iter.Accounts != nil {
				f25elem.Accounts = aws.StringSlice(f25iter.Accounts)
			}
			if f25iter.ExcludeAccounts != nil {
				f25elem.ExcludeAccounts = aws.StringSlice(f25iter.ExcludeAccounts)
			}
			if f25iter.ExecutionRoleName != nil {
				f25elem.ExecutionRoleName = f25iter.ExecutionRoleName
			}
			f25elem.IncludeChildOrganizationUnits = &f25iter.IncludeChildOrganizationUnits
			if f25iter.Regions != nil {
				f25elem.Regions = aws.StringSlice(f25iter.Regions)
			}
			if f25iter.TargetLocationAlarmConfiguration != nil {
				f25elemf5 := &svcapitypes.AlarmConfiguration{}
				if f25iter.TargetLocationAlarmConfiguration.Alarms != nil {
					f25elemf5f0 := []*svcapitypes.Alarm{}
					for _, f25elemf5f0iter := range f25iter.TargetLocationAlarmConfiguration.Alarms {
						f25elemf5f0elem := &svcapitypes.Alarm{}
						if f25elemf5f0iter.Name != nil {
							f25elemf5f0elem.Name = f25elemf5f0iter.Name
						}
						f25elemf5f0 = append(f25elemf5f0, f25elemf5f0elem)
					}
					f25elemf5.Alarms = f25elemf5f0
				}
				f25elemf5.IgnorePollAlarmFailure = &f25iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure
				f25elem.TargetLocationAlarmConfiguration = f25elemf5
			}
			if f25iter.TargetLocationMaxConcurrency != nil {
				f25elem.TargetLocationMaxConcurrency = f25iter.TargetLocationMaxConcurrency
			}
			if f25iter.TargetLocationMaxErrors != nil {
				f25elem.TargetLocationMaxErrors = f25iter.TargetLocationMaxErrors
			}
			if f25iter.Targets != nil {
				f25elemf8 := []*svcapitypes.Target{}
				for _, f25elemf8iter := range f25iter.Targets {
					f25elemf8elem := &svcapitypes.Target{}
					if f25elemf8iter.Key != nil {
						f25elemf8elem.Key = f25elemf8iter.Key
					}
					if f25elemf8iter.Values != nil {
						f25elemf8elem.Values = aws.StringSlice(f25elemf8iter.Values)
					}
					f25elemf8 = append(f25elemf8, f25elemf8elem)
				}
				f25elem.Targets = f25elemf8
			}
			if f25iter.TargetsMaxConcurrency != nil {
				f25elem.TargetsMaxConcurrency = f25iter.TargetsMaxConcurrency
			}
			if f25iter.TargetsMaxErrors != nil {
				f25elem.TargetsMaxErrors = f25iter.TargetsMaxErrors
			}
			f25 = append(f25, f25elem)
		}
		ko.Spec.TargetLocations = f25
	} else {
		ko.Spec.TargetLocations = nil
	}
	if resp.AssociationDescription.Targets != nil {
		f26 := []*svcapitypes.Target{}
		for _, f26iter := range resp.AssociationDescription.Targets {
			f26elem := &svcapitypes.Target{}
			if f26iter.Key != nil {
				f26elem.Key = f26iter.Key
			}
			if f26iter.Values != nil {
				f26elem.Values = aws.StringSlice(f26iter.Values)
			}
			f26 = append(f26, f26elem)
		}
		ko.Spec.Targets = f26
	} else {
		ko.Spec.Targets = nil
	}
	if resp.AssociationDescription.TriggeredAlarms != nil {
		f27 := []*svcapitypes.AlarmStateInformation{}
		for _, f27iter := range resp.AssociationDescription.TriggeredAlarms {
			f27elem := &svcapitypes.AlarmStateInformation{}
			if f27iter.Name != nil {
				f27elem.Name = f27iter.Name
			}
			if f27iter.State != "" {
				f27elem.State = aws.String(string(f27iter.State))
			}
			f27 = append(f27, f27elem)
		}
		ko.Status.TriggeredAlarms = f27
	} else {
		ko.Status.TriggeredAlarms = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateAssociationInput, error) {
	res := &svcsdk.CreateAssociationInput{}

	if r.ko.Spec.AlarmConfiguration != nil {
		f0 := &svcsdktypes.AlarmConfiguration{}
		if r.ko.Spec.AlarmConfiguration.Alarms != nil {
			f0f0 := []svcsdktypes.Alarm{}
			for _, f0f0iter := range r.ko.Spec.AlarmConfiguration.Alarms {
				f0f0elem := &svcsdktypes.Alarm{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = f0f0iter.Name
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.Alarms = f0f0
		}
		if r.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure != nil {
			f0.IgnorePollAlarmFailure = *r.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure
		}
		res.AlarmConfiguration = f0
	}
	if r.ko.Spec.ApplyOnlyAtCronInterval != nil {
		res.ApplyOnlyAtCronInterval = *r.ko.Spec.ApplyOnlyAtCronInterval
	}
	if r.ko.Spec.AssociationName != nil {
		res.AssociationName = r.ko.Spec.AssociationName
	}
	if r.ko.Spec.AutomationTargetParameterName != nil {
		res.AutomationTargetParameterName = r.ko.Spec.AutomationTargetParameterName
	}
	if r.ko.Spec.CalendarNames != nil {
		res.CalendarNames = aws.ToStringSlice(r.ko.Spec.CalendarNames)
	}
	if r.ko.Spec.ComplianceSeverity != nil {
		res.ComplianceSeverity = svcsdktypes.AssociationComplianceSeverity(*r.ko.Spec.ComplianceSeverity)
	}
	if r.ko.Spec.DocumentVersion != nil {
		res.DocumentVersion = r.ko.Spec.DocumentVersion
	}
	if r.ko.Spec.Duration != nil {
		durationCopy0 := *r.ko.Spec.Duration
		if durationCopy0 > math.MaxInt32 || durationCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Duration is of type int32")
		}
		durationCopy := int32(durationCopy0)
		res.Duration = &durationCopy
	}
	if r.ko.Spec.InstanceID != nil {
		res.InstanceId = r.ko.Spec.InstanceID
	}
	if r.ko.Spec.MaxConcurrency != nil {
		res.MaxConcurrency = r.ko.Spec.MaxConcurrency
	}
	if r.ko.Spec.MaxErrors != nil {
		res.MaxErrors = r.ko.Spec.MaxErrors
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.OutputLocation != nil {
		f12 := &svcsdktypes.InstanceAssociationOutputLocation{}
		if r.ko.Spec.OutputLocation.S3Location != nil {
			f12f0 := &svcsdktypes.S3OutputLocation{}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3BucketName != nil {
				f12f0.OutputS3BucketName = r.ko.Spec.OutputLocation.S3Location.OutputS3BucketName
			}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				f12f0.OutputS3KeyPrefix = r.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix
			}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3Region != nil {
				f12f0.OutputS3Region = r.ko.Spec.OutputLocation.S3Location.OutputS3Region
			}
			f12.S3Location = f12f0
		}
		res.OutputLocation = f12
	}
	if r.ko.Spec.Parameters != nil {
		f13 := map[string][]string{}
		for f13key, f13valiter := range r.ko.Spec.Parameters {
			f13[f13key] = aws.ToStringSlice(f13valiter)
		}
		res.Parameters = f13
	}
	if r.ko.Spec.ScheduleExpression != nil {
		res.ScheduleExpression = r.ko.Spec.ScheduleExpression
	}
	if r.ko.Spec.ScheduleOffset != nil {
		scheduleOffsetCopy0 := *r.ko.Spec.ScheduleOffset
		if scheduleOffsetCopy0 > math.MaxInt32 || scheduleOffsetCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field ScheduleOffset is of type int32")
		}
		scheduleOffsetCopy := int32(scheduleOffsetCopy0)
		res.ScheduleOffset = &scheduleOffsetCopy
	}
	if r.ko.Spec.SyncCompliance != nil {
		res.SyncCompliance = svcsdktypes.AssociationSyncCompliance(*r.ko.Spec.SyncCompliance)
	}
	if r.ko.Spec.Tags != nil {
		f17 := []svcsdktypes.Tag{}
		for _, f17iter := range r.ko.Spec.Tags {
			f17elem := &svcsdktypes.Tag{}
			if f17iter.Key != nil {
				f17elem.Key = f17iter.Key
			}
			if f17iter.Value != nil {
				f17elem.Value = f17iter.Value
			}
			f17 = append(f17, *f17elem)
		}
		res.Tags = f17
	}
	if r.ko.Spec.TargetLocations != nil {
		f18 := []svcsdktypes.TargetLocation{}
		for _, f18iter := range r.ko.Spec.TargetLocations {
			f18elem := &svcsdktypes.TargetLocation{}
			if f18iter.Accounts != nil {
				f18elem.Accounts = aws.ToStringSlice(f18iter.Accounts)
			}
			if f18iter.ExcludeAccounts != nil {
				f18elem.ExcludeAccounts = aws.ToStringSlice(f18iter.ExcludeAccounts)
			}
			if f18iter.ExecutionRoleName != nil {
				f18elem.ExecutionRoleName = f18iter.ExecutionRoleName
			}
			if f18iter.IncludeChildOrganizationUnits != nil {
				f18elem.IncludeChildOrganizationUnits = *f18iter.IncludeChildOrganizationUnits
			}
			if f18iter.Regions != nil {
				f18elem.Regions = aws.ToStringSlice(f18iter.Regions)
			}
			if f18iter.TargetLocationAlarmConfiguration != nil {
				f18elemf5 := &svcsdktypes.AlarmConfiguration{}
				if f18iter.TargetLocationAlarmConfiguration.Alarms != nil {
					f18elemf5f0 := []svcsdktypes.Alarm{}
					for _, f18elemf5f0iter := range f18iter.TargetLocationAlarmConfiguration.Alarms {
						f18elemf5f0elem := &svcsdktypes.Alarm{}
						if f18elemf5f0iter.Name != nil {
							f18elemf5f0elem.Name = f18elemf5f0iter.Name
						}
						f18elemf5f0 = append(f18elemf5f0, *f18elemf5f0elem)
					}
					f18elemf5.Alarms = f18elemf5f0
				}
				if f18iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure != nil {
					f18elemf5.IgnorePollAlarmFailure = *f18iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure
				}
				f18elem.TargetLocationAlarmConfiguration = f18elemf5
			}
			if f18iter.TargetLocationMaxConcurrency != nil {
				f18elem.TargetLocationMaxConcurrency = f18iter.TargetLocationMaxConcurrency
			}
			if f18iter.TargetLocationMaxErrors != nil {
				f18elem.TargetLocationMaxErrors = f18iter.TargetLocationMaxErrors
			}
			if f18iter.Targets != nil {
				f18elemf8 := []svcsdktypes.Target{}
				for _, f18elemf8iter := range f18iter.Targets {
					f18elemf8elem := &svcsdktypes.Target{}
					if f18elemf8iter.Key != nil {
						f18elemf8elem.Key = f18elemf8iter.Key
					}
					if f18elemf8iter.Values != nil {
						f18elemf8elem.Values = aws.ToStringSlice(f18elemf8iter.Values)
					}
					f18elemf8 = append(f18elemf8, *f18elemf8elem)
				}
				f18elem.Targets = f18elemf8
			}
			if f18iter.TargetsMaxConcurrency != nil {
				f18elem.TargetsMaxConcurrency = f18iter.TargetsMaxConcurrency
			}
			if f18iter.TargetsMaxErrors != nil {
				f18elem.TargetsMaxErrors = f18iter.TargetsMaxErrors
			}
			f18 = append(f18, *f18elem)
		}
		res.TargetLocations = f18
	}
	if r.ko.Spec.Targets != nil {
		f19 := []svcsdktypes.Target{}
		for _, f19iter := range r.ko.Spec.Targets {
			f19elem := &svcsdktypes.Target{}
			if f19iter.Key != nil {
				f19elem.Key = f19iter.Key
			}
			if f19iter.Values != nil {
				f19elem.Values = aws.ToStringSlice(f19iter.Values)
			}
			f19 = append(f19, *f19elem)
		}
		res.Targets = f19
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateAssociationOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateAssociation(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateAssociation", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AssociationDescription.AlarmConfiguration != nil {
		f0 := &svcapitypes.AlarmConfiguration{}
		if resp.AssociationDescription.AlarmConfiguration.Alarms != nil {
			f0f0 := []*svcapitypes.Alarm{}
			for _, f0f0iter := range resp.AssociationDescription.AlarmConfiguration.Alarms {
				f0f0elem := &svcapitypes.Alarm{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = f0f0iter.Name
				}
				f0f0 = append(f0f0, f0f0elem)
			}
			f0.Alarms = f0f0
		}
		f0.IgnorePollAlarmFailure = &resp.AssociationDescription.AlarmConfiguration.IgnorePollAlarmFailure
		ko.Spec.AlarmConfiguration = f0
	} else {
		ko.Spec.AlarmConfiguration = nil
	}
	ko.Spec.ApplyOnlyAtCronInterval = &resp.AssociationDescription.ApplyOnlyAtCronInterval
	if resp.AssociationDescription.AssociationId != nil {
		ko.Status.AssociationID = resp.AssociationDescription.AssociationId
	} else {
		ko.Status.AssociationID = nil
	}
	if resp.AssociationDescription.AssociationName != nil {
		ko.Spec.AssociationName = resp.AssociationDescription.AssociationName
	} else {
		ko.Spec.AssociationName = nil
	}
	if resp.AssociationDescription.AssociationVersion != nil {
		ko.Status.AssociationVersion = resp.AssociationDescription.AssociationVersion
	} else {
		ko.Status.AssociationVersion = nil
	}
	if resp.AssociationDescription.AutomationTargetParameterName != nil {
		ko.Spec.AutomationTargetParameterName = resp.AssociationDescription.AutomationTargetParameterName
	} else {
		ko.Spec.AutomationTargetParameterName = nil
	}
	if resp.AssociationDescription.CalendarNames != nil {
		ko.Spec.CalendarNames = aws.StringSlice(resp.AssociationDescription.CalendarNames)
	} else {
		ko.Spec.CalendarNames = nil
	}
	if resp.AssociationDescription.ComplianceSeverity != "" {
		ko.Spec.ComplianceSeverity = aws.String(string(resp.AssociationDescription.ComplianceSeverity))
	} else {
		ko.Spec.ComplianceSeverity = nil
	}
	if resp.AssociationDescription.Date != nil {
		ko.Status.Date = &metav1.Time{*resp.AssociationDescription.Date}
	} else {
		ko.Status.Date = nil
	}
	if resp.AssociationDescription.DocumentVersion != nil {
		ko.Spec.DocumentVersion = resp.AssociationDescription.DocumentVersion
	} else {
		ko.Spec.DocumentVersion = nil
	}
	if resp.AssociationDescription.Duration != nil {
		durationCopy := int64(*resp.AssociationDescription.Duration)
		ko.Spec.Duration = &durationCopy
	} else {
		ko.Spec.Duration = nil
	}
	if resp.AssociationDescription.InstanceId != nil {
		ko.Spec.InstanceID = resp.AssociationDescription.InstanceId
	} else {
		ko.Spec.InstanceID = nil
	}
	if resp.AssociationDescription.LastExecutionDate != nil {
		ko.Status.LastExecutionDate = &metav1.Time{*resp.AssociationDescription.LastExecutionDate}
	} else {
		ko.Status.LastExecutionDate = nil
	}
	if resp.AssociationDescription.LastSuccessfulExecutionDate != nil {
		ko.Status.LastSuccessfulExecutionDate = &metav1.Time{*resp.AssociationDescription.LastSuccessfulExecutionDate}
	} else {
		ko.Status.LastSuccessfulExecutionDate = nil
	}
	if resp.AssociationDescription.LastUpdateAssociationDate != nil {
		ko.Status.LastUpdateAssociationDate = &metav1.Time{*resp.AssociationDescription.LastUpdateAssociationDate}
	} else {
		ko.Status.LastUpdateAssociationDate = nil
	}
	if resp.AssociationDescription.MaxConcurrency != nil {
		ko.Spec.MaxConcurrency = resp.AssociationDescription.MaxConcurrency
	} else {
		ko.Spec.MaxConcurrency = nil
	}
	if resp.AssociationDescription.MaxErrors != nil {
		ko.Spec.MaxErrors = resp.AssociationDescription.MaxErrors
	} else {
		ko.Spec.MaxErrors = nil
	}
	if resp.AssociationDescription.Name != nil {
		ko.Spec.Name = resp.AssociationDescription.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.AssociationDescription.OutputLocation != nil {
		f18 := &svcapitypes.InstanceAssociationOutputLocation{}
		if resp.AssociationDescription.OutputLocation.S3Location != nil {
			f18f0 := &svcapitypes.S3OutputLocation{}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName != nil {
				f18f0.OutputS3BucketName = resp.AssociationDescription.OutputLocation.S3Location.OutputS3BucketName
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				f18f0.OutputS3KeyPrefix = resp.AssociationDescription.OutputLocation.S3Location.OutputS3KeyPrefix
			}
			if resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region != nil {
				f18f0.OutputS3Region = resp.AssociationDescription.OutputLocation.S3Location.OutputS3Region
			}
			f18.S3Location = f18f0
		}
		ko.Spec.OutputLocation = f18
	} else {
		ko.Spec.OutputLocation = nil
	}
	if resp.AssociationDescription.Overview != nil {
		f19 := &svcapitypes.AssociationOverview{}
		if resp.AssociationDescription.Overview.DetailedStatus != nil {
			f19.DetailedStatus = resp.AssociationDescription.Overview.DetailedStatus
		}
		if resp.AssociationDescription.Overview.Status != nil {
			f19.Status = resp.AssociationDescription.Overview.Status
		}
		ko.Status.Overview = f19
	} else {
		ko.Status.Overview = nil
	}
	if resp.AssociationDescription.Parameters != nil {
		f20 := map[string][]*string{}
		for f20key, f20valiter := range resp.AssociationDescription.Parameters {
			f20[f20key] = aws.StringSlice(f20valiter)
		}
		ko.Spec.Parameters = f20
	} else {
		ko.Spec.Parameters = nil
	}
	if resp.AssociationDescription.ScheduleExpression != nil {
		ko.Spec.ScheduleExpression = resp.AssociationDescription.ScheduleExpression
	} else {
		ko.Spec.ScheduleExpression = nil
	}
	if resp.AssociationDescription.ScheduleOffset != nil {
		scheduleOffsetCopy := int64(*resp.AssociationDescription.ScheduleOffset)
		ko.Spec.ScheduleOffset = &scheduleOffsetCopy
	} else {
		ko.Spec.ScheduleOffset = nil
	}
	if resp.AssociationDescription.Status != nil {
		f23 := &svcapitypes.AssociationStatus_SDK{}
		if resp.AssociationDescription.Status.AdditionalInfo != nil {
			f23.AdditionalInfo = resp.AssociationDescription.Status.AdditionalInfo
		}
		if resp.AssociationDescription.Status.Date != nil {
			f23.Date = &metav1.Time{*resp.AssociationDescription.Status.Date}
		}
		if resp.AssociationDescription.Status.Message != nil {
			f23.Message = resp.AssociationDescription.Status.Message
		}
		if resp.AssociationDescription.Status.Name != "" {
			f23.Name = aws.String(string(resp.AssociationDescription.Status.Name))
		}
		ko.Status.Status = f23
	} else {
		ko.Status.Status = nil
	}
	if resp.AssociationDescription.SyncCompliance != "" {
		ko.Spec.SyncCompliance = aws.String(string(resp.AssociationDescription.SyncCompliance))
	} else {
		ko.Spec.SyncCompliance = nil
	}
	if resp.AssociationDescription.TargetLocations != nil {
		f25 := []*svcapitypes.TargetLocation{}
		for _, f25iter := range resp.AssociationDescription.TargetLocations {
			f25elem := &svcapitypes.TargetLocation{}
			if f25iter.Accounts != nil {
				f25elem.Accounts = aws.StringSlice(f25iter.Accounts)
			}
			if f25iter.ExcludeAccounts != nil {
				f25elem.ExcludeAccounts = aws.StringSlice(f25iter.ExcludeAccounts)
			}
			if f25iter.ExecutionRoleName != nil {
				f25elem.ExecutionRoleName = f25iter.ExecutionRoleName
			}
			f25elem.IncludeChildOrganizationUnits = &f25iter.IncludeChildOrganizationUnits
			if f25iter.Regions != nil {
				f25elem.Regions = aws.StringSlice(f25iter.Regions)
			}
			if f25iter.TargetLocationAlarmConfiguration != nil {
				f25elemf5 := &svcapitypes.AlarmConfiguration{}
				if f25iter.TargetLocationAlarmConfiguration.Alarms != nil {
					f25elemf5f0 := []*svcapitypes.Alarm{}
					for _, f25elemf5f0iter := range f25iter.TargetLocationAlarmConfiguration.Alarms {
						f25elemf5f0elem := &svcapitypes.Alarm{}
						if f25elemf5f0iter.Name != nil {
							f25elemf5f0elem.Name = f25elemf5f0iter.Name
						}
						f25elemf5f0 = append(f25elemf5f0, f25elemf5f0elem)
					}
					f25elemf5.Alarms = f25elemf5f0
				}
				f25elemf5.IgnorePollAlarmFailure = &f25iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure
				f25elem.TargetLocationAlarmConfiguration = f25elemf5
			}
			if f25iter.TargetLocationMaxConcurrency != nil {
				f25elem.TargetLocationMaxConcurrency = f25iter.TargetLocationMaxConcurrency
			}
			if f25iter.TargetLocationMaxErrors != nil {
				f25elem.TargetLocationMaxErrors = f25iter.TargetLocationMaxErrors
			}
			if f25iter.Targets != nil {
				f25elemf8 := []*svcapitypes.Target{}
				for _, f25elemf8iter := range f25iter.Targets {
					f25elemf8elem := &svcapitypes.Target{}
					if f25elemf8iter.Key != nil {
						f25elemf8elem.Key = f25elemf8iter.Key
					}
					if f25elemf8iter.Values != nil {
						f25elemf8elem.Values = aws.StringSlice(f25elemf8iter.Values)
					}
					f25elemf8 = append(f25elemf8, f25elemf8elem)
				}
				f25elem.Targets = f25elemf8
			}
			if f25iter.TargetsMaxConcurrency != nil {
				f25elem.TargetsMaxConcurrency = f25iter.TargetsMaxConcurrency
			}
			if f25iter.TargetsMaxErrors != nil {
				f25elem.TargetsMaxErrors = f25iter.TargetsMaxErrors
			}
			f25 = append(f25, f25elem)
		}
		ko.Spec.TargetLocations = f25
	} else {
		ko.Spec.TargetLocations = nil
	}
	if resp.AssociationDescription.Targets != nil {
		f26 := []*svcapitypes.Target{}
		for _, f26iter := range resp.AssociationDescription.Targets {
			f26elem := &svcapitypes.Target{}
			if f26iter.Key != nil {
				f26elem.Key = f26iter.Key
			}
			if f26iter.Values != nil {
				f26elem.Values = aws.StringSlice(f26iter.Values)
			}
			f26 = append(f26, f26elem)
		}
		ko.Spec.Targets = f26
	} else {
		ko.Spec.Targets = nil
	}
	if resp.AssociationDescription.TriggeredAlarms != nil {
		f27 := []*svcapitypes.AlarmStateInformation{}
		for _, f27iter := range resp.AssociationDescription.TriggeredAlarms {
			f27elem := &svcapitypes.AlarmStateInformation{}
			if f27iter.Name != nil {
				f27elem.Name = f27iter.Name
			}
			if f27iter.State != "" {
				f27elem.State = aws.String(string(f27iter.State))
			}
			f27 = append(f27, f27elem)
		}
		ko.Status.TriggeredAlarms = f27
	} else {
		ko.Status.TriggeredAlarms = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateAssociationInput, error) {
	res := &svcsdk.UpdateAssociationInput{}

	if r.ko.Spec.AlarmConfiguration != nil {
		f0 := &svcsdktypes.AlarmConfiguration{}
		if r.ko.Spec.AlarmConfiguration.Alarms != nil {
			f0f0 := []svcsdktypes.Alarm{}
			for _, f0f0iter := range r.ko.Spec.AlarmConfiguration.Alarms {
				f0f0elem := &svcsdktypes.Alarm{}
				if f0f0iter.Name != nil {
					f0f0elem.Name = f0f0iter.Name
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.Alarms = f0f0
		}
		if r.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure != nil {
			f0.IgnorePollAlarmFailure = *r.ko.Spec.AlarmConfiguration.IgnorePollAlarmFailure
		}
		res.AlarmConfiguration = f0
	}
	if r.ko.Spec.ApplyOnlyAtCronInterval != nil {
		res.ApplyOnlyAtCronInterval = *r.ko.Spec.ApplyOnlyAtCronInterval
	}
	if r.ko.Status.AssociationID != nil {
		res.AssociationId = r.ko.Status.AssociationID
	}
	if r.ko.Spec.AssociationName != nil {
		res.AssociationName = r.ko.Spec.AssociationName
	}
	if r.ko.Status.AssociationVersion != nil {
		res.AssociationVersion = r.ko.Status.AssociationVersion
	}
	if r.ko.Spec.AutomationTargetParameterName != nil {
		res.AutomationTargetParameterName = r.ko.Spec.AutomationTargetParameterName
	}
	if r.ko.Spec.CalendarNames != nil {
		res.CalendarNames = aws.ToStringSlice(r.ko.Spec.CalendarNames)
	}
	if r.ko.Spec.ComplianceSeverity != nil {
		res.ComplianceSeverity = svcsdktypes.AssociationComplianceSeverity(*r.ko.Spec.ComplianceSeverity)
	}
	if r.ko.Spec.DocumentVersion != nil {
		res.DocumentVersion = r.ko.Spec.DocumentVersion
	}
	if r.ko.Spec.Duration != nil {
		durationCopy0 := *r.ko.Spec.Duration
		if durationCopy0 > math.MaxInt32 || durationCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field Duration is of type int32")
		}
		durationCopy := int32(durationCopy0)
		res.Duration = &durationCopy
	}
	if r.ko.Spec.MaxConcurrency != nil {
		res.MaxConcurrency = r.ko.Spec.MaxConcurrency
	}
	if r.ko.Spec.MaxErrors != nil {
		res.MaxErrors = r.ko.Spec.MaxErrors
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.OutputLocation != nil {
		f13 := &svcsdktypes.InstanceAssociationOutputLocation{}
		if r.ko.Spec.OutputLocation.S3Location != nil {
			f13f0 := &svcsdktypes.S3OutputLocation{}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3BucketName != nil {
				f13f0.OutputS3BucketName = r.ko.Spec.OutputLocation.S3Location.OutputS3BucketName
			}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix != nil {
				f13f0.OutputS3KeyPrefix = r.ko.Spec.OutputLocation.S3Location.OutputS3KeyPrefix
			}
			if r.ko.Spec.OutputLocation.S3Location.OutputS3Region != nil {
				f13f0.OutputS3Region = r.ko.Spec.OutputLocation.S3Location.OutputS3Region
			}
			f13.S3Location = f13f0
		}
		res.OutputLocation = f13
	}
	if r.ko.Spec.Parameters != nil {
		f14 := map[string][]string{}
		for f14key, f14valiter := range r.ko.Spec.Parameters {
			f14[f14key] = aws.ToStringSlice(f14valiter)
		}
		res.Parameters = f14
	}
	if r.ko.Spec.ScheduleExpression != nil {
		res.ScheduleExpression = r.ko.Spec.ScheduleExpression
	}
	if r.ko.Spec.ScheduleOffset != nil {
		scheduleOffsetCopy0 := *r.ko.Spec.ScheduleOffset
		if scheduleOffsetCopy0 > math.MaxInt32 || scheduleOffsetCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field ScheduleOffset is of type int32")
		}
		scheduleOffsetCopy := int32(scheduleOffsetCopy0)
		res.ScheduleOffset = &scheduleOffsetCopy
	}
	if r.ko.Spec.SyncCompliance != nil {
		res.SyncCompliance = svcsdktypes.AssociationSyncCompliance(*r.ko.Spec.SyncCompliance)
	}
	if r.ko.Spec.TargetLocations != nil {
		f18 := []svcsdktypes.TargetLocation{}
		for _, f18iter := range r.ko.Spec.TargetLocations {
			f18elem := &svcsdktypes.TargetLocation{}
			if f18iter.Accounts != nil {
				f18elem.Accounts = aws.ToStringSlice(f18iter.Accounts)
			}
			if f18iter.ExcludeAccounts != nil {
				f18elem.ExcludeAccounts = aws.ToStringSlice(f18iter.ExcludeAccounts)
			}
			if f18iter.ExecutionRoleName != nil {
				f18elem.ExecutionRoleName = f18iter.ExecutionRoleName
			}
			if f18iter.IncludeChildOrganizationUnits != nil {
				f18elem.IncludeChildOrganizationUnits = *f18iter.IncludeChildOrganizationUnits
			}
			if f18iter.Regions != nil {
				f18elem.Regions = aws.ToStringSlice(f18iter.Regions)
			}
			if f18iter.TargetLocationAlarmConfiguration != nil {
				f18elemf5 := &svcsdktypes.AlarmConfiguration{}
				if f18iter.TargetLocationAlarmConfiguration.Alarms != nil {
					f18elemf5f0 := []svcsdktypes.Alarm{}
					for _, f18elemf5f0iter := range f18iter.TargetLocationAlarmConfiguration.Alarms {
						f18elemf5f0elem := &svcsdktypes.Alarm{}
						if f18elemf5f0iter.Name != nil {
							f18elemf5f0elem.Name = f18elemf5f0iter.Name
						}
						f18elemf5f0 = append(f18elemf5f0, *f18elemf5f0elem)
					}
					f18elemf5.Alarms = f18elemf5f0
				}
				if f18iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure != nil {
					f18elemf5.IgnorePollAlarmFailure = *f18iter.TargetLocationAlarmConfiguration.IgnorePollAlarmFailure
				}
				f18elem.TargetLocationAlarmConfiguration = f18elemf5
			}
			if f18iter.TargetLocationMaxConcurrency != nil {
				f18elem.TargetLocationMaxConcurrency = f18iter.TargetLocationMaxConcurrency
			}
			if f18iter.TargetLocationMaxErrors != nil {
				f18elem.TargetLocationMaxErrors = f18iter.TargetLocationMaxErrors
			}
			if f18iter.Targets != nil {
				f18elemf8 := []svcsdktypes.Target{}
				for _, f18elemf8iter := range f18iter.Targets {
					f18elemf8elem := &svcsdktypes.Target{}
					if f18elemf8iter.Key != nil {
						f18elemf8elem.Key = f18elemf8iter.Key
					}
					if f18elemf8iter.Values != nil {
						f18elemf8elem.Values = aws.ToStringSlice(f18elemf8iter.Values)
					}
					f18elemf8 = append(f18elemf8, *f18elemf8elem)
				}
				f18elem.Targets = f18elemf8
			}
			if f18iter.TargetsMaxConcurrency != nil {
				f18elem.TargetsMaxConcurrency = f18iter.TargetsMaxConcurrency
			}
			if f18iter.TargetsMaxErrors != nil {
				f18elem.TargetsMaxErrors = f18iter.TargetsMaxErrors
			}
			f18 = append(f18, *f18elem)
		}
		res.TargetLocations = f18
	}
	if r.ko.Spec.Targets != nil {
		f19 := []svcsdktypes.Target{}
		for _, f19iter := range r.ko.Spec.Targets {
			f19elem := &svcsdktypes.Target{}
			if f19iter.Key != nil {
				f19elem.Key = f19iter.Key
			}
			if f19iter.Values != nil {
				f19elem.Values = aws.ToStringSlice(f19iter.Values)
			}
			f19 = append(f19, *f19elem)
		}
		res.Targets = f19
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteAssociationOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteAssociation(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteAssociation", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteAssociationInput, error) {
	res := &svcsdk.DeleteAssociationInput{}

	if r.ko.Status.AssociationID != nil {
		res.AssociationId = r.ko.Status.AssociationID
	}
	if r.ko.Spec.InstanceID != nil {
		res.InstanceId = r.ko.Spec.InstanceID
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Association,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
