// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package parameter

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AllowedPattern, b.ko.Spec.AllowedPattern) {
		delta.Add("Spec.AllowedPattern", a.ko.Spec.AllowedPattern, b.ko.Spec.AllowedPattern)
	} else if a.ko.Spec.AllowedPattern != nil && b.ko.Spec.AllowedPattern != nil {
		if *a.ko.Spec.AllowedPattern != *b.ko.Spec.AllowedPattern {
			delta.Add("Spec.AllowedPattern", a.ko.Spec.AllowedPattern, b.ko.Spec.AllowedPattern)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DataType, b.ko.Spec.DataType) {
		delta.Add("Spec.DataType", a.ko.Spec.DataType, b.ko.Spec.DataType)
	} else if a.ko.Spec.DataType != nil && b.ko.Spec.DataType != nil {
		if *a.ko.Spec.DataType != *b.ko.Spec.DataType {
			delta.Add("Spec.DataType", a.ko.Spec.DataType, b.ko.Spec.DataType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KeyID, b.ko.Spec.KeyID) {
		delta.Add("Spec.KeyID", a.ko.Spec.KeyID, b.ko.Spec.KeyID)
	} else if a.ko.Spec.KeyID != nil && b.ko.Spec.KeyID != nil {
		if *a.ko.Spec.KeyID != *b.ko.Spec.KeyID {
			delta.Add("Spec.KeyID", a.ko.Spec.KeyID, b.ko.Spec.KeyID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Policies, b.ko.Spec.Policies) {
		delta.Add("Spec.Policies", a.ko.Spec.Policies, b.ko.Spec.Policies)
	} else if a.ko.Spec.Policies != nil && b.ko.Spec.Policies != nil {
		if *a.ko.Spec.Policies != *b.ko.Spec.Policies {
			delta.Add("Spec.Policies", a.ko.Spec.Policies, b.ko.Spec.Policies)
		}
	}
	if len(a.ko.Spec.Tags) != len(b.ko.Spec.Tags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	} else if len(a.ko.Spec.Tags) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Tags, b.ko.Spec.Tags) {
			delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Tier, b.ko.Spec.Tier) {
		delta.Add("Spec.Tier", a.ko.Spec.Tier, b.ko.Spec.Tier)
	} else if a.ko.Spec.Tier != nil && b.ko.Spec.Tier != nil {
		if *a.ko.Spec.Tier != *b.ko.Spec.Tier {
			delta.Add("Spec.Tier", a.ko.Spec.Tier, b.ko.Spec.Tier)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Type, b.ko.Spec.Type) {
		delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
	} else if a.ko.Spec.Type != nil && b.ko.Spec.Type != nil {
		if *a.ko.Spec.Type != *b.ko.Spec.Type {
			delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Value, b.ko.Spec.Value) {
		delta.Add("Spec.Value", a.ko.Spec.Value, b.ko.Spec.Value)
	} else if a.ko.Spec.Value != nil && b.ko.Spec.Value != nil {
		if *a.ko.Spec.Value != *b.ko.Spec.Value {
			delta.Add("Spec.Value", a.ko.Spec.Value, b.ko.Spec.Value)
		}
	}

	return delta
}
