# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS SSM controller is a service controller for managing SSM resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon SSM
description: |-
  Manage Amazon SSM resources in AWS from within your Kubernetes cluster.


  **About Amazon SSM**


  {ADD YOUR DESCRIPTION HERE}


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: ExampleCustomKind
  spec: '{}'
- kind: SecondExampleCustomKind
  spec: '{}'
maintainers:
- name: "ssm maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon SSM Developer Resources
  url: https://aws.amazon.com/SSM/developer-resources/
