//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activation) DeepCopyInto(out *Activation) {
	*out = *in
	if in.Expired != nil {
		in, out := &in.Expired, &out.Expired
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activation.
func (in *Activation) DeepCopy() *Activation {
	if in == nil {
		return nil
	}
	out := new(Activation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlarmConfiguration) DeepCopyInto(out *AlarmConfiguration) {
	*out = *in
	if in.IgnorePollAlarmFailure != nil {
		in, out := &in.IgnorePollAlarmFailure, &out.IgnorePollAlarmFailure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlarmConfiguration.
func (in *AlarmConfiguration) DeepCopy() *AlarmConfiguration {
	if in == nil {
		return nil
	}
	out := new(AlarmConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Association) DeepCopyInto(out *Association) {
	*out = *in
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Association.
func (in *Association) DeepCopy() *Association {
	if in == nil {
		return nil
	}
	out := new(Association)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociationDescription) DeepCopyInto(out *AssociationDescription) {
	*out = *in
	if in.Date != nil {
		in, out := &in.Date, &out.Date
		*out = (*in).DeepCopy()
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulExecutionDate != nil {
		in, out := &in.LastSuccessfulExecutionDate, &out.LastSuccessfulExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateAssociationDate != nil {
		in, out := &in.LastUpdateAssociationDate, &out.LastUpdateAssociationDate
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociationDescription.
func (in *AssociationDescription) DeepCopy() *AssociationDescription {
	if in == nil {
		return nil
	}
	out := new(AssociationDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociationExecution) DeepCopyInto(out *AssociationExecution) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociationExecution.
func (in *AssociationExecution) DeepCopy() *AssociationExecution {
	if in == nil {
		return nil
	}
	out := new(AssociationExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociationExecutionTarget) DeepCopyInto(out *AssociationExecutionTarget) {
	*out = *in
	if in.LastExecutionDate != nil {
		in, out := &in.LastExecutionDate, &out.LastExecutionDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociationExecutionTarget.
func (in *AssociationExecutionTarget) DeepCopy() *AssociationExecutionTarget {
	if in == nil {
		return nil
	}
	out := new(AssociationExecutionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociationStatus) DeepCopyInto(out *AssociationStatus) {
	*out = *in
	if in.Date != nil {
		in, out := &in.Date, &out.Date
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociationStatus.
func (in *AssociationStatus) DeepCopy() *AssociationStatus {
	if in == nil {
		return nil
	}
	out := new(AssociationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssociationVersionInfo) DeepCopyInto(out *AssociationVersionInfo) {
	*out = *in
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = (*in).DeepCopy()
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssociationVersionInfo.
func (in *AssociationVersionInfo) DeepCopy() *AssociationVersionInfo {
	if in == nil {
		return nil
	}
	out := new(AssociationVersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentContent) DeepCopyInto(out *AttachmentContent) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentContent.
func (in *AttachmentContent) DeepCopy() *AttachmentContent {
	if in == nil {
		return nil
	}
	out := new(AttachmentContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentInformation) DeepCopyInto(out *AttachmentInformation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentInformation.
func (in *AttachmentInformation) DeepCopy() *AttachmentInformation {
	if in == nil {
		return nil
	}
	out := new(AttachmentInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachmentsSource) DeepCopyInto(out *AttachmentsSource) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachmentsSource.
func (in *AttachmentsSource) DeepCopy() *AttachmentsSource {
	if in == nil {
		return nil
	}
	out := new(AttachmentsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationExecution) DeepCopyInto(out *AutomationExecution) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.ExecutionEndTime != nil {
		in, out := &in.ExecutionEndTime, &out.ExecutionEndTime
		*out = (*in).DeepCopy()
	}
	if in.ExecutionStartTime != nil {
		in, out := &in.ExecutionStartTime, &out.ExecutionStartTime
		*out = (*in).DeepCopy()
	}
	if in.ScheduledTime != nil {
		in, out := &in.ScheduledTime, &out.ScheduledTime
		*out = (*in).DeepCopy()
	}
	if in.StepExecutionsTruncated != nil {
		in, out := &in.StepExecutionsTruncated, &out.StepExecutionsTruncated
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationExecution.
func (in *AutomationExecution) DeepCopy() *AutomationExecution {
	if in == nil {
		return nil
	}
	out := new(AutomationExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationExecutionMetadata) DeepCopyInto(out *AutomationExecutionMetadata) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.ExecutionEndTime != nil {
		in, out := &in.ExecutionEndTime, &out.ExecutionEndTime
		*out = (*in).DeepCopy()
	}
	if in.ExecutionStartTime != nil {
		in, out := &in.ExecutionStartTime, &out.ExecutionStartTime
		*out = (*in).DeepCopy()
	}
	if in.ScheduledTime != nil {
		in, out := &in.ScheduledTime, &out.ScheduledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationExecutionMetadata.
func (in *AutomationExecutionMetadata) DeepCopy() *AutomationExecutionMetadata {
	if in == nil {
		return nil
	}
	out := new(AutomationExecutionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineOverride) DeepCopyInto(out *BaselineOverride) {
	*out = *in
	if in.ApprovedPatchesEnableNonSecurity != nil {
		in, out := &in.ApprovedPatchesEnableNonSecurity, &out.ApprovedPatchesEnableNonSecurity
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineOverride.
func (in *BaselineOverride) DeepCopy() *BaselineOverride {
	if in == nil {
		return nil
	}
	out := new(BaselineOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Command) DeepCopyInto(out *Command) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAfter != nil {
		in, out := &in.ExpiresAfter, &out.ExpiresAfter
		*out = (*in).DeepCopy()
	}
	if in.RequestedDateTime != nil {
		in, out := &in.RequestedDateTime, &out.RequestedDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Command.
func (in *Command) DeepCopy() *Command {
	if in == nil {
		return nil
	}
	out := new(Command)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandInvocation) DeepCopyInto(out *CommandInvocation) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.RequestedDateTime != nil {
		in, out := &in.RequestedDateTime, &out.RequestedDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandInvocation.
func (in *CommandInvocation) DeepCopy() *CommandInvocation {
	if in == nil {
		return nil
	}
	out := new(CommandInvocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandPlugin) DeepCopyInto(out *CommandPlugin) {
	*out = *in
	if in.ResponseFinishDateTime != nil {
		in, out := &in.ResponseFinishDateTime, &out.ResponseFinishDateTime
		*out = (*in).DeepCopy()
	}
	if in.ResponseStartDateTime != nil {
		in, out := &in.ResponseStartDateTime, &out.ResponseStartDateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandPlugin.
func (in *CommandPlugin) DeepCopy() *CommandPlugin {
	if in == nil {
		return nil
	}
	out := new(CommandPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceExecutionSummary) DeepCopyInto(out *ComplianceExecutionSummary) {
	*out = *in
	if in.ExecutionTime != nil {
		in, out := &in.ExecutionTime, &out.ExecutionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceExecutionSummary.
func (in *ComplianceExecutionSummary) DeepCopy() *ComplianceExecutionSummary {
	if in == nil {
		return nil
	}
	out := new(ComplianceExecutionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateAssociationBatchRequestEntry) DeepCopyInto(out *CreateAssociationBatchRequestEntry) {
	*out = *in
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateAssociationBatchRequestEntry.
func (in *CreateAssociationBatchRequestEntry) DeepCopy() *CreateAssociationBatchRequestEntry {
	if in == nil {
		return nil
	}
	out := new(CreateAssociationBatchRequestEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Document) DeepCopyInto(out *Document) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Document.
func (in *Document) DeepCopy() *Document {
	if in == nil {
		return nil
	}
	out := new(Document)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Document) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDefaultVersionDescription) DeepCopyInto(out *DocumentDefaultVersionDescription) {
	*out = *in
	if in.DefaultVersion != nil {
		in, out := &in.DefaultVersion, &out.DefaultVersion
		*out = new(string)
		**out = **in
	}
	if in.DefaultVersionName != nil {
		in, out := &in.DefaultVersionName, &out.DefaultVersionName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDefaultVersionDescription.
func (in *DocumentDefaultVersionDescription) DeepCopy() *DocumentDefaultVersionDescription {
	if in == nil {
		return nil
	}
	out := new(DocumentDefaultVersionDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentDescription) DeepCopyInto(out *DocumentDescription) {
	*out = *in
	if in.ApprovedVersion != nil {
		in, out := &in.ApprovedVersion, &out.ApprovedVersion
		*out = new(string)
		**out = **in
	}
	if in.AttachmentsInformation != nil {
		in, out := &in.AttachmentsInformation, &out.AttachmentsInformation
		*out = make([]*AttachmentInformation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AttachmentInformation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Author != nil {
		in, out := &in.Author, &out.Author
		*out = new(string)
		**out = **in
	}
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CategoryEnum != nil {
		in, out := &in.CategoryEnum, &out.CategoryEnum
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = (*in).DeepCopy()
	}
	if in.DefaultVersion != nil {
		in, out := &in.DefaultVersion, &out.DefaultVersion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DocumentFormat != nil {
		in, out := &in.DocumentFormat, &out.DocumentFormat
		*out = new(string)
		**out = **in
	}
	if in.DocumentType != nil {
		in, out := &in.DocumentType, &out.DocumentType
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.HashType != nil {
		in, out := &in.HashType, &out.HashType
		*out = new(string)
		**out = **in
	}
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]*DocumentParameter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DocumentParameter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PendingReviewVersion != nil {
		in, out := &in.PendingReviewVersion, &out.PendingReviewVersion
		*out = new(string)
		**out = **in
	}
	if in.PlatformTypes != nil {
		in, out := &in.PlatformTypes, &out.PlatformTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]*DocumentRequires, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DocumentRequires)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ReviewInformation != nil {
		in, out := &in.ReviewInformation, &out.ReviewInformation
		*out = make([]*ReviewInformation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ReviewInformation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ReviewStatus != nil {
		in, out := &in.ReviewStatus, &out.ReviewStatus
		*out = new(string)
		**out = **in
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
	if in.Sha1 != nil {
		in, out := &in.Sha1, &out.Sha1
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusInformation != nil {
		in, out := &in.StatusInformation, &out.StatusInformation
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentDescription.
func (in *DocumentDescription) DeepCopy() *DocumentDescription {
	if in == nil {
		return nil
	}
	out := new(DocumentDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentFilter) DeepCopyInto(out *DocumentFilter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentFilter.
func (in *DocumentFilter) DeepCopy() *DocumentFilter {
	if in == nil {
		return nil
	}
	out := new(DocumentFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentIdentifier) DeepCopyInto(out *DocumentIdentifier) {
	*out = *in
	if in.Author != nil {
		in, out := &in.Author, &out.Author
		*out = new(string)
		**out = **in
	}
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = (*in).DeepCopy()
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DocumentFormat != nil {
		in, out := &in.DocumentFormat, &out.DocumentFormat
		*out = new(string)
		**out = **in
	}
	if in.DocumentType != nil {
		in, out := &in.DocumentType, &out.DocumentType
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.PlatformTypes != nil {
		in, out := &in.PlatformTypes, &out.PlatformTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]*DocumentRequires, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DocumentRequires)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ReviewStatus != nil {
		in, out := &in.ReviewStatus, &out.ReviewStatus
		*out = new(string)
		**out = **in
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentIdentifier.
func (in *DocumentIdentifier) DeepCopy() *DocumentIdentifier {
	if in == nil {
		return nil
	}
	out := new(DocumentIdentifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentKeyValuesFilter) DeepCopyInto(out *DocumentKeyValuesFilter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentKeyValuesFilter.
func (in *DocumentKeyValuesFilter) DeepCopy() *DocumentKeyValuesFilter {
	if in == nil {
		return nil
	}
	out := new(DocumentKeyValuesFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentList) DeepCopyInto(out *DocumentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Document, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentList.
func (in *DocumentList) DeepCopy() *DocumentList {
	if in == nil {
		return nil
	}
	out := new(DocumentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentParameter) DeepCopyInto(out *DocumentParameter) {
	*out = *in
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentParameter.
func (in *DocumentParameter) DeepCopy() *DocumentParameter {
	if in == nil {
		return nil
	}
	out := new(DocumentParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentRequires) DeepCopyInto(out *DocumentRequires) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RequireType != nil {
		in, out := &in.RequireType, &out.RequireType
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentRequires.
func (in *DocumentRequires) DeepCopy() *DocumentRequires {
	if in == nil {
		return nil
	}
	out := new(DocumentRequires)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentReviewerResponseSource) DeepCopyInto(out *DocumentReviewerResponseSource) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = (*in).DeepCopy()
	}
	if in.ReviewStatus != nil {
		in, out := &in.ReviewStatus, &out.ReviewStatus
		*out = new(string)
		**out = **in
	}
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(string)
		**out = **in
	}
	if in.UpdatedTime != nil {
		in, out := &in.UpdatedTime, &out.UpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentReviewerResponseSource.
func (in *DocumentReviewerResponseSource) DeepCopy() *DocumentReviewerResponseSource {
	if in == nil {
		return nil
	}
	out := new(DocumentReviewerResponseSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentSpec) DeepCopyInto(out *DocumentSpec) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]*AttachmentsSource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AttachmentsSource)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DocumentFormat != nil {
		in, out := &in.DocumentFormat, &out.DocumentFormat
		*out = new(string)
		**out = **in
	}
	if in.DocumentType != nil {
		in, out := &in.DocumentType, &out.DocumentType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]*DocumentRequires, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DocumentRequires)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(string)
		**out = **in
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentSpec.
func (in *DocumentSpec) DeepCopy() *DocumentSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentStatus) DeepCopyInto(out *DocumentStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ApprovedVersion != nil {
		in, out := &in.ApprovedVersion, &out.ApprovedVersion
		*out = new(string)
		**out = **in
	}
	if in.AttachmentsInformation != nil {
		in, out := &in.AttachmentsInformation, &out.AttachmentsInformation
		*out = make([]*AttachmentInformation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AttachmentInformation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Author != nil {
		in, out := &in.Author, &out.Author
		*out = new(string)
		**out = **in
	}
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CategoryEnum != nil {
		in, out := &in.CategoryEnum, &out.CategoryEnum
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = (*in).DeepCopy()
	}
	if in.DefaultVersion != nil {
		in, out := &in.DefaultVersion, &out.DefaultVersion
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.Hash != nil {
		in, out := &in.Hash, &out.Hash
		*out = new(string)
		**out = **in
	}
	if in.HashType != nil {
		in, out := &in.HashType, &out.HashType
		*out = new(string)
		**out = **in
	}
	if in.LatestVersion != nil {
		in, out := &in.LatestVersion, &out.LatestVersion
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]*DocumentParameter, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(DocumentParameter)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PendingReviewVersion != nil {
		in, out := &in.PendingReviewVersion, &out.PendingReviewVersion
		*out = new(string)
		**out = **in
	}
	if in.PlatformTypes != nil {
		in, out := &in.PlatformTypes, &out.PlatformTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReviewInformation != nil {
		in, out := &in.ReviewInformation, &out.ReviewInformation
		*out = make([]*ReviewInformation, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ReviewInformation)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ReviewStatus != nil {
		in, out := &in.ReviewStatus, &out.ReviewStatus
		*out = new(string)
		**out = **in
	}
	if in.SchemaVersion != nil {
		in, out := &in.SchemaVersion, &out.SchemaVersion
		*out = new(string)
		**out = **in
	}
	if in.Sha1 != nil {
		in, out := &in.Sha1, &out.Sha1
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusInformation != nil {
		in, out := &in.StatusInformation, &out.StatusInformation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentStatus.
func (in *DocumentStatus) DeepCopy() *DocumentStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentVersionInfo) DeepCopyInto(out *DocumentVersionInfo) {
	*out = *in
	if in.CreatedDate != nil {
		in, out := &in.CreatedDate, &out.CreatedDate
		*out = (*in).DeepCopy()
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DocumentFormat != nil {
		in, out := &in.DocumentFormat, &out.DocumentFormat
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.IsDefaultVersion != nil {
		in, out := &in.IsDefaultVersion, &out.IsDefaultVersion
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ReviewStatus != nil {
		in, out := &in.ReviewStatus, &out.ReviewStatus
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusInformation != nil {
		in, out := &in.StatusInformation, &out.StatusInformation
		*out = new(string)
		**out = **in
	}
	if in.VersionName != nil {
		in, out := &in.VersionName, &out.VersionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentVersionInfo.
func (in *DocumentVersionInfo) DeepCopy() *DocumentVersionInfo {
	if in == nil {
		return nil
	}
	out := new(DocumentVersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceAssociation) DeepCopyInto(out *InstanceAssociation) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceAssociation.
func (in *InstanceAssociation) DeepCopy() *InstanceAssociation {
	if in == nil {
		return nil
	}
	out := new(InstanceAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceAssociationStatusInfo) DeepCopyInto(out *InstanceAssociationStatusInfo) {
	*out = *in
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
	if in.ExecutionDate != nil {
		in, out := &in.ExecutionDate, &out.ExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceAssociationStatusInfo.
func (in *InstanceAssociationStatusInfo) DeepCopy() *InstanceAssociationStatusInfo {
	if in == nil {
		return nil
	}
	out := new(InstanceAssociationStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInformation) DeepCopyInto(out *InstanceInformation) {
	*out = *in
	if in.IsLatestVersion != nil {
		in, out := &in.IsLatestVersion, &out.IsLatestVersion
		*out = new(bool)
		**out = **in
	}
	if in.LastAssociationExecutionDate != nil {
		in, out := &in.LastAssociationExecutionDate, &out.LastAssociationExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.LastPingDateTime != nil {
		in, out := &in.LastPingDateTime, &out.LastPingDateTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulAssociationExecutionDate != nil {
		in, out := &in.LastSuccessfulAssociationExecutionDate, &out.LastSuccessfulAssociationExecutionDate
		*out = (*in).DeepCopy()
	}
	if in.PlatformType != nil {
		in, out := &in.PlatformType, &out.PlatformType
		*out = new(string)
		**out = **in
	}
	if in.RegistrationDate != nil {
		in, out := &in.RegistrationDate, &out.RegistrationDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInformation.
func (in *InstanceInformation) DeepCopy() *InstanceInformation {
	if in == nil {
		return nil
	}
	out := new(InstanceInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstancePatchState) DeepCopyInto(out *InstancePatchState) {
	*out = *in
	if in.LastNoRebootInstallOperationTime != nil {
		in, out := &in.LastNoRebootInstallOperationTime, &out.LastNoRebootInstallOperationTime
		*out = (*in).DeepCopy()
	}
	if in.OperationEndTime != nil {
		in, out := &in.OperationEndTime, &out.OperationEndTime
		*out = (*in).DeepCopy()
	}
	if in.OperationStartTime != nil {
		in, out := &in.OperationStartTime, &out.OperationStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstancePatchState.
func (in *InstancePatchState) DeepCopy() *InstancePatchState {
	if in == nil {
		return nil
	}
	out := new(InstancePatchState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowAutomationParameters) DeepCopyInto(out *MaintenanceWindowAutomationParameters) {
	*out = *in
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowAutomationParameters.
func (in *MaintenanceWindowAutomationParameters) DeepCopy() *MaintenanceWindowAutomationParameters {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowAutomationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowExecution) DeepCopyInto(out *MaintenanceWindowExecution) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowExecution.
func (in *MaintenanceWindowExecution) DeepCopy() *MaintenanceWindowExecution {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowExecutionTaskIdentity) DeepCopyInto(out *MaintenanceWindowExecutionTaskIdentity) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowExecutionTaskIdentity.
func (in *MaintenanceWindowExecutionTaskIdentity) DeepCopy() *MaintenanceWindowExecutionTaskIdentity {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowExecutionTaskIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowExecutionTaskInvocationIdentity) DeepCopyInto(out *MaintenanceWindowExecutionTaskInvocationIdentity) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowExecutionTaskInvocationIdentity.
func (in *MaintenanceWindowExecutionTaskInvocationIdentity) DeepCopy() *MaintenanceWindowExecutionTaskInvocationIdentity {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowExecutionTaskInvocationIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowRunCommandParameters) DeepCopyInto(out *MaintenanceWindowRunCommandParameters) {
	*out = *in
	if in.DocumentHash != nil {
		in, out := &in.DocumentHash, &out.DocumentHash
		*out = new(string)
		**out = **in
	}
	if in.DocumentHashType != nil {
		in, out := &in.DocumentHashType, &out.DocumentHashType
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowRunCommandParameters.
func (in *MaintenanceWindowRunCommandParameters) DeepCopy() *MaintenanceWindowRunCommandParameters {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowRunCommandParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsItem) DeepCopyInto(out *OpsItem) {
	*out = *in
	if in.ActualEndTime != nil {
		in, out := &in.ActualEndTime, &out.ActualEndTime
		*out = (*in).DeepCopy()
	}
	if in.ActualStartTime != nil {
		in, out := &in.ActualStartTime, &out.ActualStartTime
		*out = (*in).DeepCopy()
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
	if in.PlannedEndTime != nil {
		in, out := &in.PlannedEndTime, &out.PlannedEndTime
		*out = (*in).DeepCopy()
	}
	if in.PlannedStartTime != nil {
		in, out := &in.PlannedStartTime, &out.PlannedStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsItem.
func (in *OpsItem) DeepCopy() *OpsItem {
	if in == nil {
		return nil
	}
	out := new(OpsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsItemEventSummary) DeepCopyInto(out *OpsItemEventSummary) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsItemEventSummary.
func (in *OpsItemEventSummary) DeepCopy() *OpsItemEventSummary {
	if in == nil {
		return nil
	}
	out := new(OpsItemEventSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsItemRelatedItemSummary) DeepCopyInto(out *OpsItemRelatedItemSummary) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsItemRelatedItemSummary.
func (in *OpsItemRelatedItemSummary) DeepCopy() *OpsItemRelatedItemSummary {
	if in == nil {
		return nil
	}
	out := new(OpsItemRelatedItemSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsItemSummary) DeepCopyInto(out *OpsItemSummary) {
	*out = *in
	if in.ActualEndTime != nil {
		in, out := &in.ActualEndTime, &out.ActualEndTime
		*out = (*in).DeepCopy()
	}
	if in.ActualStartTime != nil {
		in, out := &in.ActualStartTime, &out.ActualStartTime
		*out = (*in).DeepCopy()
	}
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedTime != nil {
		in, out := &in.LastModifiedTime, &out.LastModifiedTime
		*out = (*in).DeepCopy()
	}
	if in.PlannedEndTime != nil {
		in, out := &in.PlannedEndTime, &out.PlannedEndTime
		*out = (*in).DeepCopy()
	}
	if in.PlannedStartTime != nil {
		in, out := &in.PlannedStartTime, &out.PlannedStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsItemSummary.
func (in *OpsItemSummary) DeepCopy() *OpsItemSummary {
	if in == nil {
		return nil
	}
	out := new(OpsItemSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsMetadata) DeepCopyInto(out *OpsMetadata) {
	*out = *in
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.LastModifiedDate != nil {
		in, out := &in.LastModifiedDate, &out.LastModifiedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsMetadata.
func (in *OpsMetadata) DeepCopy() *OpsMetadata {
	if in == nil {
		return nil
	}
	out := new(OpsMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	if in.LastModifiedDate != nil {
		in, out := &in.LastModifiedDate, &out.LastModifiedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterHistory) DeepCopyInto(out *ParameterHistory) {
	*out = *in
	if in.LastModifiedDate != nil {
		in, out := &in.LastModifiedDate, &out.LastModifiedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterHistory.
func (in *ParameterHistory) DeepCopy() *ParameterHistory {
	if in == nil {
		return nil
	}
	out := new(ParameterHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterMetadata) DeepCopyInto(out *ParameterMetadata) {
	*out = *in
	if in.LastModifiedDate != nil {
		in, out := &in.LastModifiedDate, &out.LastModifiedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterMetadata.
func (in *ParameterMetadata) DeepCopy() *ParameterMetadata {
	if in == nil {
		return nil
	}
	out := new(ParameterMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	if in.ReleaseDate != nil {
		in, out := &in.ReleaseDate, &out.ReleaseDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchComplianceData) DeepCopyInto(out *PatchComplianceData) {
	*out = *in
	if in.InstalledTime != nil {
		in, out := &in.InstalledTime, &out.InstalledTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchComplianceData.
func (in *PatchComplianceData) DeepCopy() *PatchComplianceData {
	if in == nil {
		return nil
	}
	out := new(PatchComplianceData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchRule) DeepCopyInto(out *PatchRule) {
	*out = *in
	if in.EnableNonSecurity != nil {
		in, out := &in.EnableNonSecurity, &out.EnableNonSecurity
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchRule.
func (in *PatchRule) DeepCopy() *PatchRule {
	if in == nil {
		return nil
	}
	out := new(PatchRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchStatus) DeepCopyInto(out *PatchStatus) {
	*out = *in
	if in.ApprovalDate != nil {
		in, out := &in.ApprovalDate, &out.ApprovalDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchStatus.
func (in *PatchStatus) DeepCopy() *PatchStatus {
	if in == nil {
		return nil
	}
	out := new(PatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedTargets) DeepCopyInto(out *ResolvedTargets) {
	*out = *in
	if in.Truncated != nil {
		in, out := &in.Truncated, &out.Truncated
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedTargets.
func (in *ResolvedTargets) DeepCopy() *ResolvedTargets {
	if in == nil {
		return nil
	}
	out := new(ResolvedTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReviewInformation) DeepCopyInto(out *ReviewInformation) {
	*out = *in
	if in.ReviewedTime != nil {
		in, out := &in.ReviewedTime, &out.ReviewedTime
		*out = (*in).DeepCopy()
	}
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReviewInformation.
func (in *ReviewInformation) DeepCopy() *ReviewInformation {
	if in == nil {
		return nil
	}
	out := new(ReviewInformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Runbook) DeepCopyInto(out *Runbook) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.DocumentVersion != nil {
		in, out := &in.DocumentVersion, &out.DocumentVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Runbook.
func (in *Runbook) DeepCopy() *Runbook {
	if in == nil {
		return nil
	}
	out := new(Runbook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSetting) DeepCopyInto(out *ServiceSetting) {
	*out = *in
	if in.LastModifiedDate != nil {
		in, out := &in.LastModifiedDate, &out.LastModifiedDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSetting.
func (in *ServiceSetting) DeepCopy() *ServiceSetting {
	if in == nil {
		return nil
	}
	out := new(ServiceSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Session) DeepCopyInto(out *Session) {
	*out = *in
	if in.DocumentName != nil {
		in, out := &in.DocumentName, &out.DocumentName
		*out = new(string)
		**out = **in
	}
	if in.EndDate != nil {
		in, out := &in.EndDate, &out.EndDate
		*out = (*in).DeepCopy()
	}
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Session.
func (in *Session) DeepCopy() *Session {
	if in == nil {
		return nil
	}
	out := new(Session)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepExecution) DeepCopyInto(out *StepExecution) {
	*out = *in
	if in.ExecutionEndTime != nil {
		in, out := &in.ExecutionEndTime, &out.ExecutionEndTime
		*out = (*in).DeepCopy()
	}
	if in.ExecutionStartTime != nil {
		in, out := &in.ExecutionStartTime, &out.ExecutionStartTime
		*out = (*in).DeepCopy()
	}
	if in.IsCritical != nil {
		in, out := &in.IsCritical, &out.IsCritical
		*out = new(bool)
		**out = **in
	}
	if in.IsEnd != nil {
		in, out := &in.IsEnd, &out.IsEnd
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepExecution.
func (in *StepExecution) DeepCopy() *StepExecution {
	if in == nil {
		return nil
	}
	out := new(StepExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}
